### ISSUE TITLE
Headphone audio

### ISSUE THREAD

**Issue by redmaner** [MiCode/mi2_kernel#8]
Audio via headphones is broken. I only hear noise on headphones.
If I disable dolbey in MIUI settings and reboot the phone, audio is fully silent on headphones. (maybe dolbey is connected with this issue?)
Speakers seems to work fine. Didn't test microphone and speaker for calling.

Some log errors regarding audio:
<3>[    2.469220] msm8930_audio_init: Not the right machine type
<3>[    2.469250] msm_audio_init: Not the right machine type

Full log: http://pastebin.com/RSt7jAVw

If you need more info regarding this issue you can sent me an email at redmaner@xiaomi.eu

**Comment by M1cha** [comment]
I think I can fix it for u

**Comment by redmaner** [comment]
That's fine too

**Comment by redmaner** [comment]
https://github.com/Redmaner/mi2_kernel/commit/dd97a32b44acc8e2d357a44fc0e6fd89c046bb6e
Fixed
