### ISSUE TITLE
List of bugs / missing parts

### ISSUE THREAD

**Issue by redmaner** [MiCode/mi2_kernel#9]
- color temperature and color saturation doesn't work in settings >> display >> Temperature and saturation 
- xiaomi Piston buttons not fully supported

**Comment by MarkH-UK** [comment]
Could we get feedback from the BSP team please? :-)

**Comment by redmaner** [comment]
We need it for this, would be great if you could help us.
http://xiaomi.eu/community/threads/mi2-mi2s-kernel-micore-for-miui-6-beta-testers-chosen.23012/
https://github.com/redmaner/Micore_kernel_aries
